export const SpaceExtend = {
  none: "var(--space-none)",
  xxs: "var(--space-xxs)",
  xs: "var(--space-xs)",
  sm: "var(--space-sm)",
  md: "var(--space-md)",
  lg: "var(--space-lg)",
  xl: "var(--space-xl)",
  "2xl": "var(--space-2xl)",
  "3xl": "var(--space-3xl)",
  "4xl": "var(--space-4xl)",
  "5xl": "var(--space-5xl)",
  "6xl": "var(--space-6xl)",
  "7xl": "var(--space-7xl)",
  "8xl": "var(--space-8xl)",
  "9xl": "var(--space-9xl)",
  "10xl": "var(--space-10xl)",
  "11xl": "var(--space-11xl)",
  full: "var(--space-full)",
};
